title: 개인정보 처리방침
description: 꿈을 찾는 우리들의 이야기
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
url: https://kojaem-app-policies.github.io
base_url: DreamStory-Privacy-Policy
github:
  pdf_url: /assets/downloads/index.pdf
plugins:
  - jekyll-seo-tag