title: 개인정보 처리방침
description: 꿈을 찾는 우리들의 이야기
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  pdf_url: /DreamStory-Privacy-Policy/assets/downloads/privacy_policy_꿈을찾는우리들의이야기
plugins:
  - jekyll-seo-tag